# config/meta.yml
meta_title: "Château de Medavy : Un domaine au coeur de l'Histoire"
meta_description: "N'attendez plus pour découvrir cette merveille de l'Orne !"
meta_image: "banner_meta.jpg" # Une image dans votre dossier app/assets/images/

