# config/meta.yml
meta_title: "Don't paddle, ZA:DL !"
meta_description: "Ne ramez plus pour organiser des activités avec vos amis !"
meta_image: "banner_meta.jpg" # Une image dans votre dossier app/assets/images/

